CREATE TABLE IF NOT EXISTS equipos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero_activo_fijo VARCHAR(100) NOT NULL UNIQUE,
    serial VARCHAR(100) NULL,
    nombre VARCHAR(200) NOT NULL,
    marca VARCHAR(100) NULL,
    modelo VARCHAR(100) NULL,
    descripcion TEXT NULL,
    categoria_id INT NOT NULL,
    zona_id INT NOT NULL,
    grupo_responsable VARCHAR(100) NULL,
    grupo_seguridad_id INT NULL,
    estado VARCHAR(50) DEFAULT 'activo',
    foto_equipo VARCHAR(255) NULL,
    fecha_registro DATE DEFAULT (CURDATE()),
    registrado_por_usuario_id INT NOT NULL,
    ultima_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificado_por_usuario_id INT NULL,
    esta_bloqueado BOOLEAN DEFAULT FALSE,
    motivo_bloqueo TEXT NULL,
    bloqueado_por_usuario_id INT NULL,
    fecha_bloqueo TIMESTAMP NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_equipos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_equipo(id),
    CONSTRAINT fk_equipos_zona FOREIGN KEY (zona_id) REFERENCES zonas(id),
    CONSTRAINT fk_equipos_grupo_seguridad FOREIGN KEY (grupo_seguridad_id) REFERENCES grupos_seguridad(id),
    CONSTRAINT fk_equipos_registrado_por FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_equipos_modificado_por FOREIGN KEY (modificado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_equipos_bloqueado_por FOREIGN KEY (bloqueado_por_usuario_id) REFERENCES usuarios(id),
    INDEX idx_equipos_numero_activo (numero_activo_fijo),
    INDEX idx_equipos_nombre (nombre),
    INDEX idx_equipos_categoria (categoria_id),
    INDEX idx_equipos_zona (zona_id),
    INDEX idx_equipos_estado (estado),
    INDEX idx_equipos_bloqueado (esta_bloqueado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
