CREATE TABLE IF NOT EXISTS ordenes_preventivas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo_unico VARCHAR(50) NOT NULL UNIQUE,
    equipo_id INT NOT NULL,
    nivel_mantenimiento_id INT NOT NULL,
    fecha_planificada DATE NOT NULL,
    hora_inicio TIME NULL,
    hora_fin TIME NULL,
    fecha_asignacion DATE NULL,
    fecha_inicio_ejecucion TIMESTAMP NULL,
    fecha_cierre_ejecucion TIMESTAMP NULL,
    estado VARCHAR(50) DEFAULT 'planificada',
    planificador_id INT NOT NULL,
    supervisor_asigno_id INT NULL,
    mantenedor_id INT NULL,
    duracion_estimada_horas DECIMAL(4,2) NOT NULL,
    duracion_real_horas DECIMAL(4,2) NULL,
    observaciones_mantenedor TEXT NULL,
    observaciones_supervisor TEXT NULL,
    motivo_suspension TEXT NULL,
    descripcion TEXT NULL,
    codigo_otp_validacion VARCHAR(6) NULL,
    generada_automaticamente BOOLEAN DEFAULT TRUE,
    creada_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizada_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_ordenes_preventivas_equipo FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    CONSTRAINT fk_ordenes_preventivas_nivel FOREIGN KEY (nivel_mantenimiento_id) REFERENCES niveles_mantenimiento(id),
    CONSTRAINT fk_ordenes_preventivas_planificador FOREIGN KEY (planificador_id) REFERENCES usuarios(id),
    CONSTRAINT fk_ordenes_preventivas_supervisor FOREIGN KEY (supervisor_asigno_id) REFERENCES usuarios(id),
    CONSTRAINT fk_ordenes_preventivas_mantenedor FOREIGN KEY (mantenedor_id) REFERENCES usuarios(id),
    INDEX idx_otp_codigo (codigo_unico),
    INDEX idx_otp_equipo (equipo_id),
    INDEX idx_otp_estado (estado),
    INDEX idx_otp_fecha_planificada (fecha_planificada),
    INDEX idx_otp_mantenedor (mantenedor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
