CREATE TABLE IF NOT EXISTS ordenes_correctivas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo_unico VARCHAR(50) NOT NULL UNIQUE,
    equipo_id INT NOT NULL,
    tipo_falla_id INT NOT NULL,
    prioridad_id INT NOT NULL,
    zona_id INT NULL,
    fecha_reporte DATE NOT NULL,
    hora_reporte TIME NOT NULL,
    reportado_por_usuario_id INT NOT NULL,
    fecha_inicio_reparacion DATE NULL,
    hora_inicio_reparacion TIME NULL,
    fecha_fin_reparacion DATE NULL,
    hora_fin_reparacion TIME NULL,
    descripcion_falla TEXT NOT NULL,
    acciones_tomadas TEXT NULL,
    causa_raiz TEXT NULL,
    repuestos_utilizados TEXT NULL,
    downtime_calculado_minutos INT NULL,
    estado VARCHAR(50) DEFAULT 'reportada',
    supervisor_asigno_id INT NULL,
    mantenedor_id INT NULL,
    cerrada_por_usuario_id INT NULL,
    fecha_cierre TIMESTAMP NULL,
    es_preventivo_fuera_de_plan BOOLEAN DEFAULT FALSE,
    es_reporte_condicion BOOLEAN DEFAULT FALSE,
    condicion_observada TEXT NULL,
    recomendacion_condicion TEXT NULL,
    orden_preventiva_relacionada_id INT NULL,
    orden_correctiva_relacionada_id INT NULL,
    creada_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_otc_equipo FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    CONSTRAINT fk_otc_tipo_falla FOREIGN KEY (tipo_falla_id) REFERENCES tipos_falla(id),
    CONSTRAINT fk_otc_prioridad FOREIGN KEY (prioridad_id) REFERENCES prioridades_falla(id),
    CONSTRAINT fk_otc_zona FOREIGN KEY (zona_id) REFERENCES zonas(id),
    CONSTRAINT fk_otc_reportado_por FOREIGN KEY (reportado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_otc_supervisor FOREIGN KEY (supervisor_asigno_id) REFERENCES usuarios(id),
    CONSTRAINT fk_otc_mantenedor FOREIGN KEY (mantenedor_id) REFERENCES usuarios(id),
    CONSTRAINT fk_otc_cerrada_por FOREIGN KEY (cerrada_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_otc_orden_preventiva_relacionada FOREIGN KEY (orden_preventiva_relacionada_id) REFERENCES ordenes_preventivas(id),
    CONSTRAINT fk_otc_orden_correctiva_relacionada FOREIGN KEY (orden_correctiva_relacionada_id) REFERENCES ordenes_correctivas(id),
    INDEX idx_otc_codigo (codigo_unico),
    INDEX idx_otc_equipo (equipo_id),
    INDEX idx_otc_estado (estado),
    INDEX idx_otc_fecha_reporte (fecha_reporte),
    INDEX idx_otc_mantenedor (mantenedor_id),
    INDEX idx_otc_es_condicion (es_reporte_condicion)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
